/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReprogramadasRouteImport } from './routes/reprogramadas'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as CadastrarEmpresaRouteImport } from './routes/cadastrar-empresa'
import { Route as CadastrarRouteImport } from './routes/cadastrar'
import { Route as AtrasadasRouteImport } from './routes/atrasadas'
import { Route as AtividadesRouteImport } from './routes/atividades'
import { Route as IndexRouteImport } from './routes/index'

const ReprogramadasRoute = ReprogramadasRouteImport.update({
  id: '/reprogramadas',
  path: '/reprogramadas',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrarEmpresaRoute = CadastrarEmpresaRouteImport.update({
  id: '/cadastrar-empresa',
  path: '/cadastrar-empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrarRoute = CadastrarRouteImport.update({
  id: '/cadastrar',
  path: '/cadastrar',
  getParentRoute: () => rootRouteImport,
} as any)
const AtrasadasRoute = AtrasadasRouteImport.update({
  id: '/atrasadas',
  path: '/atrasadas',
  getParentRoute: () => rootRouteImport,
} as any)
const AtividadesRoute = AtividadesRouteImport.update({
  id: '/atividades',
  path: '/atividades',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atividades': typeof AtividadesRoute
  '/atrasadas': typeof AtrasadasRoute
  '/cadastrar': typeof CadastrarRoute
  '/cadastrar-empresa': typeof CadastrarEmpresaRoute
  '/equipe': typeof EquipeRoute
  '/historico': typeof HistoricoRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/reprogramadas': typeof ReprogramadasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atividades': typeof AtividadesRoute
  '/atrasadas': typeof AtrasadasRoute
  '/cadastrar': typeof CadastrarRoute
  '/cadastrar-empresa': typeof CadastrarEmpresaRoute
  '/equipe': typeof EquipeRoute
  '/historico': typeof HistoricoRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/reprogramadas': typeof ReprogramadasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atividades': typeof AtividadesRoute
  '/atrasadas': typeof AtrasadasRoute
  '/cadastrar': typeof CadastrarRoute
  '/cadastrar-empresa': typeof CadastrarEmpresaRoute
  '/equipe': typeof EquipeRoute
  '/historico': typeof HistoricoRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/reprogramadas': typeof ReprogramadasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atividades'
    | '/atrasadas'
    | '/cadastrar'
    | '/cadastrar-empresa'
    | '/equipe'
    | '/historico'
    | '/login'
    | '/perfil'
    | '/reprogramadas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atividades'
    | '/atrasadas'
    | '/cadastrar'
    | '/cadastrar-empresa'
    | '/equipe'
    | '/historico'
    | '/login'
    | '/perfil'
    | '/reprogramadas'
  id:
    | '__root__'
    | '/'
    | '/atividades'
    | '/atrasadas'
    | '/cadastrar'
    | '/cadastrar-empresa'
    | '/equipe'
    | '/historico'
    | '/login'
    | '/perfil'
    | '/reprogramadas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtividadesRoute: typeof AtividadesRoute
  AtrasadasRoute: typeof AtrasadasRoute
  CadastrarRoute: typeof CadastrarRoute
  CadastrarEmpresaRoute: typeof CadastrarEmpresaRoute
  EquipeRoute: typeof EquipeRoute
  HistoricoRoute: typeof HistoricoRoute
  LoginRoute: typeof LoginRoute
  PerfilRoute: typeof PerfilRoute
  ReprogramadasRoute: typeof ReprogramadasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reprogramadas': {
      id: '/reprogramadas'
      path: '/reprogramadas'
      fullPath: '/reprogramadas'
      preLoaderRoute: typeof ReprogramadasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastrar-empresa': {
      id: '/cadastrar-empresa'
      path: '/cadastrar-empresa'
      fullPath: '/cadastrar-empresa'
      preLoaderRoute: typeof CadastrarEmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastrar': {
      id: '/cadastrar'
      path: '/cadastrar'
      fullPath: '/cadastrar'
      preLoaderRoute: typeof CadastrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atrasadas': {
      id: '/atrasadas'
      path: '/atrasadas'
      fullPath: '/atrasadas'
      preLoaderRoute: typeof AtrasadasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atividades': {
      id: '/atividades'
      path: '/atividades'
      fullPath: '/atividades'
      preLoaderRoute: typeof AtividadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtividadesRoute: AtividadesRoute,
  AtrasadasRoute: AtrasadasRoute,
  CadastrarRoute: CadastrarRoute,
  CadastrarEmpresaRoute: CadastrarEmpresaRoute,
  EquipeRoute: EquipeRoute,
  HistoricoRoute: HistoricoRoute,
  LoginRoute: LoginRoute,
  PerfilRoute: PerfilRoute,
  ReprogramadasRoute: ReprogramadasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
