// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    // We use a light read of the session to get the token.
    const { data } = await supabase.auth.getSession()
    const token = data.session?.access_token
    
    if (!token) {
      console.warn('[attachSupabaseAuth] No session token found for request')
    }
    
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  },
)
